name: 'dbt'
version: '1.0'
config-version: 2

profile: 'dbt'

source-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_modules"

models:
  my_dbt_project:
    staging:
      materialized: table
    marts:
      materialized: table
